#Skool Class Service
server:
  port: 9007
#MYSQL Properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skooltime
    username: root
    password: viswanadh
  application:
    name: Skool-Class-Service
#Hibernate Properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka
    fetch-registry: true
    register-with-eureka: true
