#Subjects Service
server:
  port: 9006
#MYSQL Properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skooltime
    username: root
    password: viswanadh
  application:
    name: Subjects-Service
#Hibernate Properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#Eureka Properties
eureka:
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://localhost:9761/eureka
