#Attendence Student Service
server:
  port: 9005

#database properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skoolTime
    username: root
    password: viswanadh
  application:
    name: "AttendenceStudentService"
    
#hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
#eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9761/eureka